# Generated by Django 5.1 on 2024-08-30 14:26

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userMobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('plan_period', models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='monthly', max_length=50)),
                ('plan_option', models.CharField(choices=[('arcade', 'Arcade'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=50)),
                ('add_on', models.TextField(blank=True)),
            ],
        ),
    ]
