# Generated by Django 5.1.1 on 2024-09-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscr',
            name='plan_option',
            field=models.CharField(choices=[('arcade', 'Arcade'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='', max_length=50),
        ),
    ]
