# Generated by Django 5.1.1 on 2024-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscr_plan_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscr',
            name='advancedMonthly',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscr',
            name='advancedYearly',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscr',
            name='arcadeMonthly',
            field=models.DecimalField(decimal_places=2, default=9.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscr',
            name='arcadeYearly',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscr',
            name='proMonthly',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subscr',
            name='proYearly',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=5),
        ),
    ]
